#!/usr/bin/env bash
# Compile the M3 shaders to SPIR-V and emit them as C uint32_t arrays in
# tri_shaders.h (embedded — no on-device shader compiler).
#   docker run --rm -v "D:\switch-nvk:/work" -w /work switch-nvk-build bash winsys/smoke/shaders/gen-shaders.sh
set -e
cd "$(dirname "$0")"
glslangValidator -V triangle.vert -o triangle.vert.spv
glslangValidator -V triangle.frag -o triangle.frag.spv
glslangValidator -V quad.vert     -o quad.vert.spv
glslangValidator -V quad.frag     -o quad.frag.spv
glslangValidator -V scene.vert    -o scene.vert.spv
glslangValidator -V scene.frag    -o scene.frag.spv
glslangValidator -V sascha_triangle.vert -o sascha_triangle.vert.spv
glslangValidator -V sascha_triangle.frag -o sascha_triangle.frag.spv
glslangValidator -V sascha_skybox.vert   -o sascha_skybox.vert.spv
glslangValidator -V sascha_skybox.frag   -o sascha_skybox.frag.spv
glslangValidator -V multi.vert    -o multi.vert.spv
glslangValidator -V multi.frag    -o multi.frag.spv
glslangValidator -V tex.vert      -o tex.vert.spv
glslangValidator -V tex.frag      -o tex.frag.spv
glslangValidator -V compute.comp  -o compute.comp.spv
python3 - <<'PY'
import struct
def emit(name, path, out):
    data = open(path,'rb').read()
    assert len(data) % 4 == 0, "SPIR-V not word-aligned"
    words = struct.unpack('<%dI' % (len(data)//4), data)
    out.write('static const uint32_t %s[] = {\n' % name)
    for i in range(0, len(words), 8):
        out.write('  ' + ', '.join('0x%08x' % w for w in words[i:i+8]) + ',\n')
    out.write('};\n')
    out.write('static const unsigned %s_sz = %d; /* bytes */\n\n' % (name, len(data)))
with open('tri_shaders.h','w') as o:
    o.write('/* generated by gen-shaders.sh — do not edit */\n')
    o.write('#pragma once\n#include <stdint.h>\n\n')
    emit('tri_vert_spv','triangle.vert.spv',o)
    emit('tri_frag_spv','triangle.frag.spv',o)
    emit('quad_vert_spv','quad.vert.spv',o)
    emit('quad_frag_spv','quad.frag.spv',o)
    emit('scene_vert_spv','scene.vert.spv',o)
    emit('scene_frag_spv','scene.frag.spv',o)
    emit('sascha_vert_spv','sascha_triangle.vert.spv',o)
    emit('sascha_frag_spv','sascha_triangle.frag.spv',o)
    emit('skybox_vert_spv','sascha_skybox.vert.spv',o)
    emit('skybox_frag_spv','sascha_skybox.frag.spv',o)
    emit('multi_vert_spv','multi.vert.spv',o)
    emit('multi_frag_spv','multi.frag.spv',o)
    emit('tex_vert_spv','tex.vert.spv',o)
    emit('tex_frag_spv','tex.frag.spv',o)
    emit('compute_spv','compute.comp.spv',o)
print('wrote tri_shaders.h (triangle + quad + scene + sascha + skybox + multi + tex SPIR-V)')
PY
ls -la tri_shaders.h
